dist: trusty
addons:
  apt:
    packages:
    - openjdk-8-jdk
    - ant
    - python2.7
    - git

before_script:
  - git clone https://github.com/facebook/buck.git
  - pushd buck && ant && popd
  - export PATH=~/buck/bin:$PATH
  - buck --version

script:
  - buck fetch //...
  - buck test //...
