sudo: false
dist: trusty
addons:
  apt:
    packages:
    - openjdk-8-jdk
    - ant
    - python2.7
    - git

before_script:
  # Install Linuxbrew
  - LINUXBREW_HOME=$HOME/tools/linuxbrew
  - git clone https://github.com/Linuxbrew/brew.git $LINUXBREW_HOME
  - PATH="$LINUXBREW_HOME/bin:$PATH"
  - echo 'export PATH="$LINUXBREW_HOME/bin:$PATH"' >>~/.bash_profile
  - export MANPATH="$(brew --prefix)/share/man:$MANPATH"
  - export INFOPATH="$(brew --prefix)/share/info:$INFOPATH"
  - brew --version
  # Install Buck
  - brew tap facebook/fb
  - brew install buck
  - buck --version

script:
  - buck fetch //...
  - buck test //...

services:
  - mongodb

cache:
  directories:
  - $HOME/buck/bin
  - $HOME/buck/programs