jms:
  activemq:
    brokers:
      - name: internal-broker
        url: ssl://localhost:2023?jms.redeliveryPolicy.maximumRedeliveries=0
        tls:
          keyStoreFilePath: ./tls_activemq/broker.ks
          keyStorePassword: brokerpassword
          trustStoreFilePath: ./tls_activemq/client.ts
          trustStorePassword: clientpassword
