jms:
  activemq:
    brokers:
      - name: internal-broker
        url: vm://embedded-broker?create=false&jms.redeliveryPolicy.maximumRedeliveries=0
        readOnly: true
        read:
          frequency: 5
          timeUnit: SECONDS
